//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.DocumentFill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentSubmitUserControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentSubmitUserControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.DocumentFill.DocumentSubmitUserControl", typeof(DocumentSubmitUserControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is already approved and it is read only.
        /// </summary>
        public static string ApprovedNotes {
            get {
                return ResourceManager.GetString("ApprovedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is expired and it is read only.
        /// </summary>
        public static string ExpiredNotes {
            get {
                return ResourceManager.GetString("ExpiredNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document requires a hard signature. Once you complete all pages, you will be prompted to print and upload the signed document..
        /// </summary>
        public static string ExplanatoryNotes {
            get {
                return ResourceManager.GetString("ExplanatoryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / View Page Comments.
        /// </summary>
        public static string PageComments {
            get {
                return ResourceManager.GetString("PageComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Denied:.
        /// </summary>
        public static string PageDeniedMessage {
            get {
                return ResourceManager.GetString("PageDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document needs to be signed and submitted, you can.
        /// </summary>
        public static string PrintDocumentPart1 {
            get {
                return ResourceManager.GetString("PrintDocumentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or fill it and print it later.
        /// </summary>
        public static string PrintDocumentPart2 {
            get {
                return ResourceManager.GetString("PrintDocumentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print it now.
        /// </summary>
        public static string PrintItNow {
            get {
                return ResourceManager.GetString("PrintItNow", resourceCulture);
            }
        }
    }
}
