//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.DocumentFill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentComplete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentComplete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.DocumentFill.DocumentComplete", typeof(DocumentComplete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to complete the document?.
        /// </summary>
        public static string ContinueToDocumentMessage {
            get {
                return ResourceManager.GetString("ContinueToDocumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is already approved, you cannot modify it.
        /// </summary>
        public static string DocumentApprovedTitle {
            get {
                return ResourceManager.GetString("DocumentApprovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be notified if the document is approved or denied.
        /// </summary>
        public static string DocumentCompletedSubtitle {
            get {
                return ResourceManager.GetString("DocumentCompletedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully completed this document.
        /// </summary>
        public static string DocumentCompletedTitle {
            get {
                return ResourceManager.GetString("DocumentCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is expired, you cannot modify it.
        /// </summary>
        public static string DocumentExpiredTitle {
            get {
                return ResourceManager.GetString("DocumentExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Document.
        /// </summary>
        public static string DownloadDocument {
            get {
                return ResourceManager.GetString("DownloadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to refill.
        /// </summary>
        public static string EditDocumentMessage_Part2 {
            get {
                return ResourceManager.GetString("EditDocumentMessage_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you found any mistakes?.
        /// </summary>
        public static string EditDocumentMessage_Parte1 {
            get {
                return ResourceManager.GetString("EditDocumentMessage_Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string LinkMessage {
            get {
                return ResourceManager.GetString("LinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can continue with the rest of the documents and come back to complete this one later..
        /// </summary>
        public static string PartiallyCompletedSubtitle {
            get {
                return ResourceManager.GetString("PartiallyCompletedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have partially completed this document.
        /// </summary>
        public static string PartiallyCompletedTitle {
            get {
                return ResourceManager.GetString("PartiallyCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to print the document?.
        /// </summary>
        public static string PrintDocumentMessage {
            get {
                return ResourceManager.GetString("PrintDocumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished reading this document..
        /// </summary>
        public static string ReadOnlyTitle {
            get {
                return ResourceManager.GetString("ReadOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to see what was approved?.
        /// </summary>
        public static string ViewApprovedDocument {
            get {
                return ResourceManager.GetString("ViewApprovedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to see the document?.
        /// </summary>
        public static string ViewExpiredDocument {
            get {
                return ResourceManager.GetString("ViewExpiredDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to see what you&apos;ve uploaded?.
        /// </summary>
        public static string ViewUploadedDocument {
            get {
                return ResourceManager.GetString("ViewUploadedDocument", resourceCulture);
            }
        }
    }
}
