//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.DocumentFill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentHardSignatureOptionsUserControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentHardSignatureOptionsUserControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.DocumentFill.DocumentHardSignatureOptionsU" +
                            "serControl", typeof(DocumentHardSignatureOptionsUserControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a.
        /// </summary>
        public static string DocumentPages_Part1 {
            get {
                return ResourceManager.GetString("DocumentPages_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page document. Please make sure the PDF you upload has the same number of pages..
        /// </summary>
        public static string DocumentPages_Part2 {
            get {
                return ResourceManager.GetString("DocumentPages_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View uploaded document.
        /// </summary>
        public static string DownloadBttn {
            get {
                return ResourceManager.GetString("DownloadBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click on Print Document the document will be downloaded in PDF format.  You must have a PDF Viewer in order to open and print this document..
        /// </summary>
        public static string DownloadExplanatoryNotes {
            get {
                return ResourceManager.GetString("DownloadExplanatoryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit document.
        /// </summary>
        public static string EditBttn {
            get {
                return ResourceManager.GetString("EditBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you found any mistakes?.
        /// </summary>
        public static string EditDocument_Part1 {
            get {
                return ResourceManager.GetString("EditDocument_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to refill.
        /// </summary>
        public static string EditDocument_Part2 {
            get {
                return ResourceManager.GetString("EditDocument_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are almost done, this document needs to be printed, signed and uploaded to be completed.
        /// </summary>
        public static string ExplanatoryNotes {
            get {
                return ResourceManager.GetString("ExplanatoryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax document later.
        /// </summary>
        public static string FaxDocument {
            get {
                return ResourceManager.GetString("FaxDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string LinkMessage {
            get {
                return ResourceManager.GetString("LinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum upload file size:.
        /// </summary>
        public static string MaxUploadSize {
            get {
                return ResourceManager.GetString("MaxUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may download the free Adobe® Reader at.
        /// </summary>
        public static string PdfReaderNotes {
            get {
                return ResourceManager.GetString("PdfReaderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print document.
        /// </summary>
        public static string PrintBttn {
            get {
                return ResourceManager.GetString("PrintBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document.
        /// </summary>
        public static string UploadBttn {
            get {
                return ResourceManager.GetString("UploadBttn", resourceCulture);
            }
        }
    }
}
