//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.DocumentFill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentFaxDocumentUserControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentFaxDocumentUserControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.DocumentFill.DocumentFaxDocumentUserContro" +
                            "l", typeof(DocumentFaxDocumentUserControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to fax the document later. The document will remain pending until it is uploaded or faxed..
        /// </summary>
        public static string ExplanatoryNotes {
            get {
                return ResourceManager.GetString("ExplanatoryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For faxing the.
        /// </summary>
        public static string FaxInformationPart1 {
            get {
                return ResourceManager.GetString("FaxInformationPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please fax to the HR secure fax line:.
        /// </summary>
        public static string FaxInformationPart2 {
            get {
                return ResourceManager.GetString("FaxInformationPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wanted to upload the.
        /// </summary>
        public static string UploadInformationPart1 {
            get {
                return ResourceManager.GetString("UploadInformationPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click on the.
        /// </summary>
        public static string UploadInformationPart2 {
            get {
                return ResourceManager.GetString("UploadInformationPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link below, and select Upload document..
        /// </summary>
        public static string UploadInformationPart3 {
            get {
                return ResourceManager.GetString("UploadInformationPart3", resourceCulture);
            }
        }
    }
}
