//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.DocumentFill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.DocumentFill.Index2", typeof(Index2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in this category are approved..
        /// </summary>
        public static string Approved_Help {
            get {
                return ResourceManager.GetString("Approved_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change selection here.
        /// </summary>
        public static string ChangeDocSelection {
            get {
                return ResourceManager.GetString("ChangeDocSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to change the selection. Please refresh the page and try again..
        /// </summary>
        public static string ChangeDocumentError {
            get {
                return ResourceManager.GetString("ChangeDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocCenter 6.
        /// </summary>
        public static string DocCenter {
            get {
                return ResourceManager.GetString("DocCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in this category are expired and can not be modified..
        /// </summary>
        public static string Expired_Help {
            get {
                return ResourceManager.GetString("Expired_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Filled {
            get {
                return ResourceManager.GetString("Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in this category are submitted and pending approval..
        /// </summary>
        public static string Filled_Help {
            get {
                return ResourceManager.GetString("Filled_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string GoBackToHome {
            get {
                return ResourceManager.GetString("GoBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Concourse - Help.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading the page. Please try again later.
        /// </summary>
        public static string LoadingError {
            get {
                return ResourceManager.GetString("LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem retrieving the document. Please try again later..
        /// </summary>
        public static string LoadPageError {
            get {
                return ResourceManager.GetString("LoadPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Comments.
        /// </summary>
        public static string PageCommentsTitle {
            get {
                return ResourceManager.GetString("PageCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocCenter | HRConcourse.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a partial document. You can view the original document .
        /// </summary>
        public static string PartialDocumentPages1 {
            get {
                return ResourceManager.GetString("PartialDocumentPages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string PartialDocumentPages2 {
            get {
                return ResourceManager.GetString("PartialDocumentPages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in this category require your action, this documents need to be filled..
        /// </summary>
        public static string Pending_Help {
            get {
                return ResourceManager.GetString("Pending_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in this category are provided for information..
        /// </summary>
        public static string ReadOnly_Help {
            get {
                return ResourceManager.GetString("ReadOnly_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show less.
        /// </summary>
        public static string ShowLessErrors {
            get {
                return ResourceManager.GetString("ShowLessErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show more.
        /// </summary>
        public static string ShowMoreErrors {
            get {
                return ResourceManager.GetString("ShowMoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while submitting the comments. Please try again later..
        /// </summary>
        public static string SubmitCommentsError {
            get {
                return ResourceManager.GetString("SubmitCommentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comments have been correctly submitted..
        /// </summary>
        public static string SubmitCommentsSuccess {
            get {
                return ResourceManager.GetString("SubmitCommentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem submitting the page. Please try again later..
        /// </summary>
        public static string SubmitError {
            get {
                return ResourceManager.GetString("SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit page comments.
        /// </summary>
        public static string SubmitPageComments {
            get {
                return ResourceManager.GetString("SubmitPageComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting....
        /// </summary>
        public static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while uploading the document. Please try again later..
        /// </summary>
        public static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload one document at a time..
        /// </summary>
        public static string UploadMultipleFilesError {
            get {
                return ResourceManager.GetString("UploadMultipleFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded document doesn&apos;t have the required amount of pages..
        /// </summary>
        public static string UploadPageNumberError {
            get {
                return ResourceManager.GetString("UploadPageNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded document can not be parsed correctly..
        /// </summary>
        public static string UploadParsingError {
            get {
                return ResourceManager.GetString("UploadParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string WelcomeSection {
            get {
                return ResourceManager.GetString("WelcomeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Documents.
        /// </summary>
        public static string YourDocuments {
            get {
                return ResourceManager.GetString("YourDocuments", resourceCulture);
            }
        }
    }
}
