//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.DocumentFill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Summary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.DocumentFill.Summary", typeof(Summary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is expired.
        /// </summary>
        public static string DocumentExpired {
            get {
                return ResourceManager.GetString("DocumentExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Approved.
        /// </summary>
        public static string DocumentsApproved {
            get {
                return ResourceManager.GetString("DocumentsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Pending Approval.
        /// </summary>
        public static string DocumentsPendingApproval {
            get {
                return ResourceManager.GetString("DocumentsPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Summary.
        /// </summary>
        public static string DocumentSummary {
            get {
                return ResourceManager.GetString("DocumentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document contains errors.
        /// </summary>
        public static string DocumentWithErrors {
            get {
                return ResourceManager.GetString("DocumentWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Documents.
        /// </summary>
        public static string MissingDocuments {
            get {
                return ResourceManager.GetString("MissingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Hard Signature.
        /// </summary>
        public static string RequiresHardSignature {
            get {
                return ResourceManager.GetString("RequiresHardSignature", resourceCulture);
            }
        }
    }
}
