//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Areas.Filler.Resources.FormBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Areas.Filler.Resources.FormBuilder.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the following values.
        /// </summary>
        internal static string AddInitialValueMessage {
            get {
                return ResourceManager.GetString("AddInitialValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add initial value.
        /// </summary>
        internal static string AddInitialValueTitle {
            get {
                return ResourceManager.GetString("AddInitialValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ConfirmActionMessage {
            get {
                return ResourceManager.GetString("ConfirmActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmActionTitle {
            get {
                return ResourceManager.GetString("ConfirmActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property when you want the initial value of this date field to be the current date, such as when the user is filling the form.
        /// </summary>
        internal static string CurrentDate_Help {
            get {
                return ResourceManager.GetString("CurrentDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is used to compare the equity between this field&apos;s value and the selected field&apos;s value..
        /// </summary>
        internal static string Equals_Help {
            get {
                return ResourceManager.GetString("Equals_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This read-only property contains the unique identifier of the field..
        /// </summary>
        internal static string FieldID_Help {
            get {
                return ResourceManager.GetString("FieldID_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the field&apos;s name. Use a name that easily conveys its purpose. Example: &quot;FirstName&quot;.
        /// </summary>
        internal static string FieldName_Help {
            get {
                return ResourceManager.GetString("FieldName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string FilterInitialValueMessage {
            get {
                return ResourceManager.GetString("FilterInitialValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the field&apos;s font size in pixels..
        /// </summary>
        internal static string FontSize_Help {
            get {
                return ResourceManager.GetString("FontSize_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property if you want to make the checkboxes to behave as a group, i.e. only one can be selected..
        /// </summary>
        internal static string Grouping_Help {
            get {
                return ResourceManager.GetString("Grouping_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to specify the URL of the page the link goes to.
        /// </summary>
        internal static string Href_Help {
            get {
                return ResourceManager.GetString("Href_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to set the initial value for the field. Using the plus sign will show a list of all the available values. Example value: &quot;2/4/2012&quot;.
        /// </summary>
        internal static string InitialValue_Help {
            get {
                return ResourceManager.GetString("InitialValue_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires javascript enabled.
        /// </summary>
        internal static string JavaScriptWarningMessage {
            get {
                return ResourceManager.GetString("JavaScriptWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the maximum date that the user will be allowed to select for this field..
        /// </summary>
        internal static string MaxDate_Help {
            get {
                return ResourceManager.GetString("MaxDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the maximum length of characters that the user should enter for this field..
        /// </summary>
        internal static string MaxLength_Help {
            get {
                return ResourceManager.GetString("MaxLength_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the maximum number that the user will be allowed to enter for this field..
        /// </summary>
        internal static string MaxNumber_Help {
            get {
                return ResourceManager.GetString("MaxNumber_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the minimum date that the user will be allowed to select for this field..
        /// </summary>
        internal static string MinDate_Help {
            get {
                return ResourceManager.GetString("MinDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the minimum length of characters that the user should enter for this field..
        /// </summary>
        internal static string MinLength_Help {
            get {
                return ResourceManager.GetString("MinLength_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the minimum number that the user will be allowed to enter for this field..
        /// </summary>
        internal static string MinNumber_Help {
            get {
                return ResourceManager.GetString("MinNumber_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to indicate the minimum of selected checkboxes that the user should check..
        /// </summary>
        internal static string MinSelected_Help {
            get {
                return ResourceManager.GetString("MinSelected_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to mark the field as an out field, indicating the corresponding name when needed..
        /// </summary>
        internal static string OutField_Help {
            get {
                return ResourceManager.GetString("OutField_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property when you want to restrict the user&apos;s input, indicating the regular expresion that it must match..
        /// </summary>
        internal static string Pattern_Help {
            get {
                return ResourceManager.GetString("Pattern_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to mark the field as read-only.
        /// </summary>
        internal static string ReadOnly_Help {
            get {
                return ResourceManager.GetString("ReadOnly_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to mark the field as required to fill.
        /// </summary>
        internal static string Required_Help {
            get {
                return ResourceManager.GetString("Required_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property represents the text displayed on the select field when no value has been selected..
        /// </summary>
        internal static string SelectTitle_Help {
            get {
                return ResourceManager.GetString("SelectTitle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show less.
        /// </summary>
        internal static string ShowLessErrors {
            get {
                return ResourceManager.GetString("ShowLessErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show more.
        /// </summary>
        internal static string ShowMoreErrors {
            get {
                return ResourceManager.GetString("ShowMoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is used to select the source from where to populate the select field&apos;s values..
        /// </summary>
        internal static string Source_Help {
            get {
                return ResourceManager.GetString("Source_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property if you want to modify the default  tab order for the field..
        /// </summary>
        internal static string TabIndex_Help {
            get {
                return ResourceManager.GetString("TabIndex_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this property to set a tooltip that will appear over the field on hover. Example: &quot;Introduce your birth date&quot; .
        /// </summary>
        internal static string Tooltip_Help {
            get {
                return ResourceManager.GetString("Tooltip_Help", resourceCulture);
            }
        }
    }
}
