//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentInstanceFiles
    {
        public System.Guid DocumentInstanceId { get; set; }
        public byte[] FileData { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string MimeType { get; set; }
    
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPageTranslations
    {
        public DocumentPageTranslations()
        {
            this.PageFieldTranslations = new HashSet<PageFieldTranslations>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DocumentPageId { get; set; }
        public string Language { get; set; }
        public Nullable<System.Guid> DocumentPageImageId { get; set; }
    
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage { get; set; }
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage1 { get; set; }
        public virtual ObjRoots_PageImage ObjRoots_PageImage { get; set; }
        public virtual ICollection<PageFieldTranslations> PageFieldTranslations { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergeFieldInstanceValues
    {
        public System.Guid DocumentInstanceId { get; set; }
        public System.Guid MergeFieldId { get; set; }
        public byte[] Value { get; set; }
        public bool HasChanged { get; set; }
    
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
        public virtual ObjRoots_MergeField ObjRoots_MergeField { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots
    {
        public System.Guid Id { get; set; }
        public System.Guid HierId { get; set; }
        public bool IsActive { get; set; }
        public bool IsTestData { get; set; }
        public string SearchKey { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> CurrentUserId { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_ComboGroup
    {
        public string Name { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_Document
    {
        public ObjRoots_Document()
        {
            this.ObjRoots_Document1 = new HashSet<ObjRoots_Document>();
            this.ObjRoots_DocumentPage = new HashSet<ObjRoots_DocumentPage>();
            this.ObjRoots_Document11 = new HashSet<ObjRoots_Document>();
            this.ObjRoots_DocumentInstance = new HashSet<ObjRoots_DocumentInstance>();
            this.ObjRoots_Document12 = new HashSet<ObjRoots_Document>();
            this.ObjRoots_DocumentPackage = new HashSet<ObjRoots_DocumentPackage>();
        }
    
        public string Name { get; set; }
        public bool RequiresHardSignature { get; set; }
        public int DaysToExpire { get; set; }
        public string OriginalLanguage { get; set; }
        public Nullable<System.Guid> DocumentTypeId { get; set; }
        public Nullable<System.Guid> OverriddenByDocumentId { get; set; }
        public Nullable<System.Guid> ParentDocumentId { get; set; }
        public Nullable<System.Guid> ChildTypeMergeFieldId { get; set; }
        public string ChildTypeMergeFieldValue { get; set; }
        public System.Guid Id { get; set; }
        public bool IsReadOnly { get; set; }
        public int Revision { get; set; }
        public Nullable<System.DateTime> DocumentExpirationDate { get; set; }
        public Nullable<bool> InstantiateParent { get; set; }
        public bool IsReadyForInstantiation { get; set; }
        public bool AutoExpire { get; set; }
        public int Order { get; set; }
        public Nullable<System.Guid> TranslationOfDocumentId { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document1 { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document2 { get; set; }
        public virtual ObjRoots_MergeField ObjRoots_MergeField { get; set; }
        public virtual ICollection<ObjRoots_DocumentPage> ObjRoots_DocumentPage { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document11 { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document3 { get; set; }
        public virtual ObjRoots_DocumentType ObjRoots_DocumentType { get; set; }
        public virtual ICollection<ObjRoots_DocumentInstance> ObjRoots_DocumentInstance { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document12 { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document4 { get; set; }
        public virtual ICollection<ObjRoots_DocumentPackage> ObjRoots_DocumentPackage { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentInstance
    {
        public ObjRoots_DocumentInstance()
        {
            this.MergeFieldInstanceValues = new HashSet<MergeFieldInstanceValues>();
            this.ObjRoots_DocumentInstance1 = new HashSet<ObjRoots_DocumentInstance>();
            this.ObjRoots_DocumentPageInstance = new HashSet<ObjRoots_DocumentPageInstance>();
            this.ObjRoots_DocumentInstanceMessage = new HashSet<ObjRoots_DocumentInstanceMessage>();
        }
    
        public bool IsRequired { get; set; }
        public bool Enabled { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ExtenalGuid { get; set; }
        public System.Guid DocumentId { get; set; }
        public Nullable<int> OverrideType { get; set; }
        public string OverrideReason { get; set; }
        public Nullable<System.Guid> OverriddenByInstanceId { get; set; }
        public System.DateTime InstantiationDate { get; set; }
        public string Recipient { get; set; }
        public string Email { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsManuallyExpired { get; set; }
        public bool IsExternallySubmitted { get; set; }
    
        public virtual DocumentInstanceFiles DocumentInstanceFiles { get; set; }
        public virtual ICollection<MergeFieldInstanceValues> MergeFieldInstanceValues { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document { get; set; }
        public virtual ICollection<ObjRoots_DocumentInstance> ObjRoots_DocumentInstance1 { get; set; }
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance2 { get; set; }
        public virtual ICollection<ObjRoots_DocumentPageInstance> ObjRoots_DocumentPageInstance { get; set; }
        public virtual ICollection<ObjRoots_DocumentInstanceMessage> ObjRoots_DocumentInstanceMessage { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentInstanceLog
    {
        public System.Guid ExternalId { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentInstanceMessage
    {
        public System.Guid Id { get; set; }
        public System.Guid DocumentInstanceId { get; set; }
        public string Description { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentPackage
    {
        public ObjRoots_DocumentPackage()
        {
            this.ObjRoots_Document = new HashSet<ObjRoots_Document>();
        }
    
        public string Name { get; set; }
        public bool IsRequired { get; set; }
        public System.Guid Id { get; set; }
        public bool IsKiosk { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentPage
    {
        public ObjRoots_DocumentPage()
        {
            this.DocumentPageTranslations = new HashSet<DocumentPageTranslations>();
            this.DocumentPageTranslations1 = new HashSet<DocumentPageTranslations>();
            this.ObjRoots_DocumentPageInstance = new HashSet<ObjRoots_DocumentPageInstance>();
            this.ObjRoots_PageField = new HashSet<ObjRoots_PageField>();
            this.ObjRoots_PageField1 = new HashSet<ObjRoots_PageField>();
        }
    
        public short Number { get; set; }
        public System.Guid DocumentId { get; set; }
        public Nullable<System.Guid> DocumentPageImageId { get; set; }
        public System.Guid Id { get; set; }
        public bool Instantiate { get; set; }
    
        public virtual ICollection<DocumentPageTranslations> DocumentPageTranslations { get; set; }
        public virtual ICollection<DocumentPageTranslations> DocumentPageTranslations1 { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document { get; set; }
        public virtual ObjRoots_PageImage ObjRoots_PageImage { get; set; }
        public virtual ICollection<ObjRoots_DocumentPageInstance> ObjRoots_DocumentPageInstance { get; set; }
        public virtual ICollection<ObjRoots_PageField> ObjRoots_PageField { get; set; }
        public virtual ICollection<ObjRoots_PageField> ObjRoots_PageField1 { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentPageInstance
    {
        public Nullable<bool> Approved { get; set; }
        public string NotApprovedReason { get; set; }
        public System.Guid DocumentPageId { get; set; }
        public string UserComments { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> FillDate { get; set; }
        public System.Guid DocumentInstanceId { get; set; }
        public byte[] PreRenderedPDFPage { get; set; }
        public System.Guid Id { get; set; }
        public byte[] SubmittedData { get; set; }
        public byte[] DraftData { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentType
    {
        public ObjRoots_DocumentType()
        {
            this.ObjRoots_Document = new HashSet<ObjRoots_Document>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid Id { get; set; }
        public long FillMode { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_ExternalGuidFillToken
    {
        public System.Guid ExternalGuid { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_MergeField
    {
        public ObjRoots_MergeField()
        {
            this.MergeFieldInstanceValues = new HashSet<MergeFieldInstanceValues>();
            this.ObjRoots_Document = new HashSet<ObjRoots_Document>();
        }
    
        public string Key { get; set; }
        public string TestValue { get; set; }
        public System.Guid Id { get; set; }
        public bool IsPostBack { get; set; }
        public long FieldType { get; set; }
        public Nullable<int> DecimalPrecision { get; set; }
        public Nullable<bool> ShowTime { get; set; }
    
        public virtual ICollection<MergeFieldInstanceValues> MergeFieldInstanceValues { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_Notification
    {
        public System.Guid TemplateId { get; set; }
        public System.Guid ConditionId { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_PageField
    {
        public ObjRoots_PageField()
        {
            this.PageFieldTranslations = new HashSet<PageFieldTranslations>();
        }
    
        public string FieldId { get; set; }
        public string FieldName { get; set; }
        public string Tooltip { get; set; }
        public System.Guid DocumentPageId { get; set; }
        public int FieldType { get; set; }
        public string Html { get; set; }
        public string InitialValue { get; set; }
        public bool IsOutField { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public Nullable<short> TabIndex { get; set; }
        public bool Required { get; set; }
        public string Pattern { get; set; }
        public Nullable<short> MinimumLength { get; set; }
        public Nullable<short> MaxLength { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<short> MinSelected { get; set; }
        public string DataEquals { get; set; }
        public Nullable<bool> UseCurrentDate { get; set; }
        public string RangeDateMin { get; set; }
        public string RangeDateMax { get; set; }
        public Nullable<short> DependencyCount { get; set; }
        public string SelectTitle { get; set; }
        public string SelectFieldSource { get; set; }
        public string SelectPrefixedSource { get; set; }
        public string DependencyData { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public Nullable<bool> RangeDateMinUseCurrent { get; set; }
        public Nullable<bool> RangeDateMaxUseCurrent { get; set; }
        public string Style { get; set; }
        public System.Guid Id { get; set; }
        public string Href { get; set; }
        public Nullable<System.Guid> OutFieldId { get; set; }
        public Nullable<short> CustomValidationCount { get; set; }
        public string CustomValidationData { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage { get; set; }
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage1 { get; set; }
        public virtual ICollection<PageFieldTranslations> PageFieldTranslations { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_PageImage
    {
        public ObjRoots_PageImage()
        {
            this.DocumentPageTranslations = new HashSet<DocumentPageTranslations>();
            this.ObjRoots_DocumentPage = new HashSet<ObjRoots_DocumentPage>();
        }
    
        public byte[] Image { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ICollection<DocumentPageTranslations> DocumentPageTranslations { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_DocumentPage> ObjRoots_DocumentPage { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageFieldTranslations
    {
        public System.Guid Id { get; set; }
        public System.Guid DocumentPageTranslationId { get; set; }
        public System.Guid PageFieldId { get; set; }
        public string Tooltip { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public string Html { get; set; }
        public string InitialValue { get; set; }
        public string SelectTitle { get; set; }
        public string Href { get; set; }
    
        public virtual DocumentPageTranslations DocumentPageTranslations { get; set; }
        public virtual ObjRoots_PageField ObjRoots_PageField { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_DataMotions
    {
        public int DataMotionId { get; set; }
        public System.DateTime DateExcecuted { get; set; }
        public bool IsPreDeploy { get; set; }
    }
}
namespace HRConcourse.Web.cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTokens
    {
        public long Id { get; set; }
        public string TokenString { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
    }
}
