// <auto-generated />
namespace HRConcourse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateABP_to_0_7_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateABP_to_0_7_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201510222131387_updateABP_to_0_7_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
