//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HRConcourse.Web.cor;

namespace HRConcourse.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRConcourseCoreEntities : DbContext
    {
        public HRConcourseCoreEntities()
            : base("name=HRConcourseCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<ConfigurationValues> ConfigurationValues { get; set; }
        public virtual DbSet<EmailAccountDefaults> EmailAccountDefaults { get; set; }
        public virtual DbSet<EmailTemplateFields> EmailTemplateFields { get; set; }
        public virtual DbSet<Hiers> Hiers { get; set; }
        public virtual DbSet<HierTypes> HierTypes { get; set; }
        public virtual DbSet<Logger> Logger { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<ObjRoots> ObjRoots { get; set; }
        public virtual DbSet<ObjRoots_EmailTemplate> ObjRoots_EmailTemplate { get; set; }
        public virtual DbSet<ObjRoots_HierVisualProfile> ObjRoots_HierVisualProfile { get; set; }
        public virtual DbSet<ObjRoots_MailBoxes> ObjRoots_MailBoxes { get; set; }
        public virtual DbSet<ObjRoots_SLMessage> ObjRoots_SLMessage { get; set; }
        public virtual DbSet<ObjRoots_TemplateCategoryDefaults> ObjRoots_TemplateCategoryDefaults { get; set; }
        public virtual DbSet<ProfileProperties> ProfileProperties { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<uScriptAllText> uScriptAllText { get; set; }
        public virtual DbSet<UserHierRoles> UserHierRoles { get; set; }
        public virtual DbSet<UserModules> UserModules { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserVisitedURLs> UserVisitedURLs { get; set; }
    }
}
