//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAccountDefaults
    {
        public System.Guid EmailAccountTypeId { get; set; }
        public string ServerName { get; set; }
        public Nullable<int> IncomingPort { get; set; }
        public string IncomingServerAddress { get; set; }
        public Nullable<bool> IncomingUseSSL { get; set; }
        public Nullable<int> OutgoingPort { get; set; }
        public string OutgoingServerAddress { get; set; }
        public Nullable<bool> OutgoingUseSSL { get; set; }
    }
}
