//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hiers
    {
        public Hiers()
        {
            this.Hiers1 = new HashSet<Hiers>();
            this.ObjRoots = new HashSet<ObjRoots>();
            this.Users = new HashSet<Users>();
            this.UserHierRoles = new HashSet<UserHierRoles>();
            this.Modules = new HashSet<Modules>();
        }
    
        public System.Guid HierId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentHierId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> ExternalHierId { get; set; }
        public string WebName { get; set; }
        public string KioskCallbackUrl { get; set; }
        public System.Guid HierTypeId { get; set; }
    
        public virtual ICollection<Hiers> Hiers1 { get; set; }
        public virtual Hiers Hiers2 { get; set; }
        public virtual ICollection<ObjRoots> ObjRoots { get; set; }
        public virtual HierTypes HierTypes { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<UserHierRoles> UserHierRoles { get; set; }
        public virtual ICollection<Modules> Modules { get; set; }
    }
}
