//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public long LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogMsg1 { get; set; }
        public string LogMsg2 { get; set; }
        public Nullable<System.Guid> MiscId1 { get; set; }
        public Nullable<System.Guid> MiscId2 { get; set; }
    }
}
