//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.UserModules = new HashSet<UserModules>();
            this.Hiers = new HashSet<Hiers>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string XapName { get; set; }
    
        public virtual ICollection<UserModules> UserModules { get; set; }
        public virtual ICollection<Hiers> Hiers { get; set; }
    }
}
