//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_EmailTemplate
    {
        public ObjRoots_EmailTemplate()
        {
            this.EmailTemplateFields = new HashSet<EmailTemplateFields>();
            this.ObjRoots_TemplateCategoryDefaults = new HashSet<ObjRoots_TemplateCategoryDefaults>();
        }
    
        public string SubjectTemplate { get; set; }
        public string BodyTemplate { get; set; }
        public System.Guid CategoryId { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.Guid> DefaultMailBoxId { get; set; }
        public System.Guid Id { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
    
        public virtual ICollection<EmailTemplateFields> EmailTemplateFields { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_TemplateCategoryDefaults> ObjRoots_TemplateCategoryDefaults { get; set; }
    }
}
