//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots
    {
        public System.Guid Id { get; set; }
        public System.Guid HierId { get; set; }
        public bool IsTestData { get; set; }
        public System.Guid PrimaryUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> MigrationId { get; set; }
    }
}
