//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_MailBoxes
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string IncomingServerAddress { get; set; }
        public int IncomingPort { get; set; }
        public bool IncomingUseSSL { get; set; }
        public string OutgoingServerAddress { get; set; }
        public int OutgoingPort { get; set; }
        public bool OutgoingUseSSL { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
    }
}
