//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_TemplateCategoryDefaults
    {
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.Guid TemplateId { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_EmailTemplate ObjRoots_EmailTemplate { get; set; }
    }
}
