//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.UserHierRoles = new HashSet<UserHierRoles>();
        }
    
        public string Name { get; set; }
        public bool IsDefault { get; set; }
        public System.Guid RoleId { get; set; }
        public bool IsHierCreateDefault { get; set; }
    
        public virtual ICollection<UserHierRoles> UserHierRoles { get; set; }
    }
}
