//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class uScriptAllText
    {
        public int ID { get; set; }
        public string ObjectType { get; set; }
        public string ObjectName { get; set; }
        public bool IsCreateLine { get; set; }
        public string Txt { get; set; }
    }
}
