//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHierRoles
    {
        public System.Guid UserId { get; set; }
        public System.Guid HierId { get; set; }
        public System.Guid RoleId { get; set; }
    
        public virtual Hiers Hiers { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
