//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.ObjRoots = new HashSet<ObjRoots>();
            this.ProfileProperties = new HashSet<ProfileProperties>();
            this.UserHierRoles = new HashSet<UserHierRoles>();
            this.UserModules = new HashSet<UserModules>();
        }
    
        public System.Guid UserId { get; set; }
        public string MobileAlias { get; set; }
        public Nullable<System.Guid> CurrentHierId { get; set; }
        public string Email { get; set; }
        public string FriendlyName { get; set; }
        public byte[] Password { get; set; }
        public bool ForceUpdatePassword { get; set; }
        public Nullable<System.DateTime> LastPasswordUpdateDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsTestMode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long ViewModeEnum { get; set; }
        public string Username { get; set; }
        public bool IsKiosk { get; set; }
    
        public virtual Hiers Hiers { get; set; }
        public virtual ICollection<ObjRoots> ObjRoots { get; set; }
        public virtual ICollection<ProfileProperties> ProfileProperties { get; set; }
        public virtual ICollection<UserHierRoles> UserHierRoles { get; set; }
        public virtual ICollection<UserModules> UserModules { get; set; }
    }
}
