//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRConcourse.Web.Localization.FormBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CSS_StyleProperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSS_StyleProperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRConcourse.Web.Localization.FormBuilder.CSS_StyleProperties", typeof(CSS_StyleProperties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background shorthand property sets all the background properties in one declaration. The properties that can be set, are: background-color, background-position, background-size, background-repeat, background-origin, background-clip, background-attachment, and background-image. Syntax: color position size repeat origin clip attachment image.
        /// </summary>
        public static string Background_Help {
            get {
                return ResourceManager.GetString("Background_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background-attachment property sets whether a background image is fixed or scrolls with the rest of the page..
        /// </summary>
        public static string BackgroundAttachment_Help {
            get {
                return ResourceManager.GetString("BackgroundAttachment_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background-color property sets the background color of an element..
        /// </summary>
        public static string BackgroundColor_Help {
            get {
                return ResourceManager.GetString("BackgroundColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background-image property sets the background image for an element. By default, a background-image is placed at the top-left corner of an element, and repeated both vertically and horizontally. Syntax: url(stars.gif).
        /// </summary>
        public static string BackgroundImage_Help {
            get {
                return ResourceManager.GetString("BackgroundImage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background-position property sets the starting position of a background image. Note: For this to work in Firefox and Opera, the background-attachment property must be set to &quot;fixed&quot;..
        /// </summary>
        public static string BackgroundPosition_Help {
            get {
                return ResourceManager.GetString("BackgroundPosition_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background-repeat property sets if/how a background image will be repeated. By default, a background-image is repeated both vertically and horizontally..
        /// </summary>
        public static string BackgroundRepeat_Help {
            get {
                return ResourceManager.GetString("BackgroundRepeat_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border shorthand property sets all the border properties in one declaration. The properties that can be set, are (in order): border-width, border-style, and border-color. Syntax: width style color.
        /// </summary>
        public static string Border_Help {
            get {
                return ResourceManager.GetString("Border_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-bottom-color property sets the color of an element&apos;s bottom border..
        /// </summary>
        public static string BorderBottomColor_Help {
            get {
                return ResourceManager.GetString("BorderBottomColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-left-style property sets the style of an element&apos;s bottom border..
        /// </summary>
        public static string BorderBottomStyle_Help {
            get {
                return ResourceManager.GetString("BorderBottomStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-right-width property sets the width of an element&apos;s bottom border..
        /// </summary>
        public static string BorderBottomWidth_Help {
            get {
                return ResourceManager.GetString("BorderBottomWidth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-color property sets the color of an element&apos;s four borders..
        /// </summary>
        public static string BorderColor_Help {
            get {
                return ResourceManager.GetString("BorderColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-left-color property sets the color of an element&apos;s left border..
        /// </summary>
        public static string BorderLeftColor_Help {
            get {
                return ResourceManager.GetString("BorderLeftColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-left-style property sets the style of an element&apos;s left border..
        /// </summary>
        public static string BorderLeftStyle_Help {
            get {
                return ResourceManager.GetString("BorderLeftStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-right-width property sets the width of an element&apos;s left border..
        /// </summary>
        public static string BorderLeftWidth_Help {
            get {
                return ResourceManager.GetString("BorderLeftWidth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-right-color property sets the color of an element&apos;s right border..
        /// </summary>
        public static string BorderRightColor_Help {
            get {
                return ResourceManager.GetString("BorderRightColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-left-style property sets the style of an element&apos;s right border..
        /// </summary>
        public static string BorderRightStyle_Help {
            get {
                return ResourceManager.GetString("BorderRightStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-right-width property sets the width of an element&apos;s right border..
        /// </summary>
        public static string BorderRightWidth_Help {
            get {
                return ResourceManager.GetString("BorderRightWidth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-style property sets the style of an element&apos;s four borders..
        /// </summary>
        public static string BorderStyle_Help {
            get {
                return ResourceManager.GetString("BorderStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-top-color property sets the color of an element&apos;s top border..
        /// </summary>
        public static string BorderTopColor_Help {
            get {
                return ResourceManager.GetString("BorderTopColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-left-style property sets the style of an element&apos;s top border..
        /// </summary>
        public static string BorderTopStyle_Help {
            get {
                return ResourceManager.GetString("BorderTopStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-right-width property sets the width of an element&apos;s top border..
        /// </summary>
        public static string BorderTopWidth_Help {
            get {
                return ResourceManager.GetString("BorderTopWidth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border-width property sets the width of an element&apos;s four borders. Example: 1px 2px 1px 2px.
        /// </summary>
        public static string BorderWidth_Help {
            get {
                return ResourceManager.GetString("BorderWidth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color property specifies the color of text..
        /// </summary>
        public static string Color_Help {
            get {
                return ResourceManager.GetString("Color_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cursor property specifies the type of cursor to be displayed when pointing on an element..
        /// </summary>
        public static string Cursor_Help {
            get {
                return ResourceManager.GetString("Cursor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display property defines how a certain HTML element should be displayed..
        /// </summary>
        public static string Display_Help {
            get {
                return ResourceManager.GetString("Display_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font shorthand property sets all the font properties in one declaration. The properties that can be set, are (in order): &quot;font-style font-variant font-weight font-size font-family&quot;The font-size and font-family values are required. If one of the other values are missing, the default values will be inserted, if any..
        /// </summary>
        public static string Font_Help {
            get {
                return ResourceManager.GetString("Font_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font-family property specifies the font for an element. The font-family property can hold several font names as a &quot;fallback&quot; system. If the browser does not support the first font, it tries the next font. If a font name contains white-space, it must be quoted. Single quotes must be used when using the &quot;style&quot; attribute in HTML. Example: &quot;Times New Roman&quot;,Georgia,Serif;.
        /// </summary>
        public static string FontFamily_Help {
            get {
                return ResourceManager.GetString("FontFamily_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font-size property sets the size of a font..
        /// </summary>
        public static string FontSize_Help {
            get {
                return ResourceManager.GetString("FontSize_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font-style property specifies the font style for a text..
        /// </summary>
        public static string FontStyle_Help {
            get {
                return ResourceManager.GetString("FontStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font-variant property specifies whether or not a text should be displayed in a small-caps font. In a small-caps font, all lowercase letters are converted to uppercase letters. However, the converted uppercase letters appears in a smaller font size than the original uppercase letters in the text..
        /// </summary>
        public static string FontVariant_Help {
            get {
                return ResourceManager.GetString("FontVariant_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font-weight property sets how thick or thin characters in text should be displayed..
        /// </summary>
        public static string FontWeight_Help {
            get {
                return ResourceManager.GetString("FontWeight_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The letter-spacing property increases or decreases the space between characters in a text..
        /// </summary>
        public static string LetterSpacing_Help {
            get {
                return ResourceManager.GetString("LetterSpacing_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opacity property sets the opacity level for an element. From 0.0 (fully transparent) to 1.0 (fully opaque).
        /// </summary>
        public static string Opacity_Help {
            get {
                return ResourceManager.GetString("Opacity_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An outline is a line that is drawn around elements (outside the borders) to make the element &quot;stand out&quot;. The outline shorthand property sets all the outline properties in one declaration. The properties that can be set, are (in order): outline-color, outline-style, outline-width. If one of the values above are missing, e.g. &quot;outline:solid #ff0000;&quot;, the default value for the missing property will be inserted, if any..
        /// </summary>
        public static string Outline_Help {
            get {
                return ResourceManager.GetString("Outline_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outline-color property specifies the color of an outline..
        /// </summary>
        public static string OutlineColor_Help {
            get {
                return ResourceManager.GetString("OutlineColor_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outline-style property specifies the style of an outline..
        /// </summary>
        public static string OutlineStyle_Help {
            get {
                return ResourceManager.GetString("OutlineStyle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outline-width specifies the width of an outline..
        /// </summary>
        public static string OutlineWidth_Help {
            get {
                return ResourceManager.GetString("OutlineWidth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text-align property specifies the horizontal alignment of text in an element..
        /// </summary>
        public static string TextAlign_Help {
            get {
                return ResourceManager.GetString("TextAlign_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text-decoration property specifies the decoration added to text..
        /// </summary>
        public static string TextDecoration_Help {
            get {
                return ResourceManager.GetString("TextDecoration_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text-indent property specifies the indentation of the first line in a text-block..
        /// </summary>
        public static string TextIndent_Help {
            get {
                return ResourceManager.GetString("TextIndent_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text-transform property controls the capitalization of text..
        /// </summary>
        public static string TextTransform_Help {
            get {
                return ResourceManager.GetString("TextTransform_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word-spacing property increases or decreases the white space between words..
        /// </summary>
        public static string WordSpacing_Help {
            get {
                return ResourceManager.GetString("WordSpacing_Help", resourceCulture);
            }
        }
    }
}
