//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergeFieldInstanceValues
    {
        public System.Guid DocumentInstanceId { get; set; }
        public System.Guid MergeFieldId { get; set; }
        public byte[] Value { get; set; }
        public bool HasChanged { get; set; }
    
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
        public virtual ObjRoots_MergeField ObjRoots_MergeField { get; set; }
    }
}
