//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_MergeField
    {
        public ObjRoots_MergeField()
        {
            this.MergeFieldInstanceValues = new HashSet<MergeFieldInstanceValues>();
            this.ObjRoots_Document = new HashSet<ObjRoots_Document>();
        }
    
        public string Key { get; set; }
        public string TestValue { get; set; }
        public System.Guid Id { get; set; }
        public bool IsPostBack { get; set; }
        public long FieldType { get; set; }
        public Nullable<int> DecimalPrecision { get; set; }
        public Nullable<bool> ShowTime { get; set; }
    
        public virtual ICollection<MergeFieldInstanceValues> MergeFieldInstanceValues { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ICollection<ObjRoots_Document> ObjRoots_Document { get; set; }
    }
}
