//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentInstance
    {
        public ObjRoots_DocumentInstance()
        {
            this.MergeFieldInstanceValues = new HashSet<MergeFieldInstanceValues>();
            this.ObjRoots_DocumentInstance1 = new HashSet<ObjRoots_DocumentInstance>();
            this.ObjRoots_DocumentPageInstance = new HashSet<ObjRoots_DocumentPageInstance>();
            this.ObjRoots_DocumentInstanceMessage = new HashSet<ObjRoots_DocumentInstanceMessage>();
        }
    
        public bool IsRequired { get; set; }
        public bool Enabled { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ExtenalGuid { get; set; }
        public System.Guid DocumentId { get; set; }
        public Nullable<int> OverrideType { get; set; }
        public string OverrideReason { get; set; }
        public Nullable<System.Guid> OverriddenByInstanceId { get; set; }
        public System.DateTime InstantiationDate { get; set; }
        public string Recipient { get; set; }
        public string Email { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsManuallyExpired { get; set; }
        public bool IsExternallySubmitted { get; set; }
    
        public virtual DocumentInstanceFiles DocumentInstanceFiles { get; set; }
        public virtual ICollection<MergeFieldInstanceValues> MergeFieldInstanceValues { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document { get; set; }
        public virtual ICollection<ObjRoots_DocumentInstance> ObjRoots_DocumentInstance1 { get; set; }
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance2 { get; set; }
        public virtual ICollection<ObjRoots_DocumentPageInstance> ObjRoots_DocumentPageInstance { get; set; }
        public virtual ICollection<ObjRoots_DocumentInstanceMessage> ObjRoots_DocumentInstanceMessage { get; set; }
    }
}
