//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentInstanceLog
    {
        public System.Guid ExternalId { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
    }
}
