//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentPage
    {
        public ObjRoots_DocumentPage()
        {
            this.DocumentPageTranslations = new HashSet<DocumentPageTranslations>();
            this.DocumentPageTranslations1 = new HashSet<DocumentPageTranslations>();
            this.ObjRoots_DocumentPageInstance = new HashSet<ObjRoots_DocumentPageInstance>();
            this.ObjRoots_PageField = new HashSet<ObjRoots_PageField>();
            this.ObjRoots_PageField1 = new HashSet<ObjRoots_PageField>();
        }
    
        public short Number { get; set; }
        public System.Guid DocumentId { get; set; }
        public Nullable<System.Guid> DocumentPageImageId { get; set; }
        public System.Guid Id { get; set; }
        public bool Instantiate { get; set; }
    
        public virtual ICollection<DocumentPageTranslations> DocumentPageTranslations { get; set; }
        public virtual ICollection<DocumentPageTranslations> DocumentPageTranslations1 { get; set; }
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document1 { get; set; }
        public virtual ObjRoots_PageImage ObjRoots_PageImage { get; set; }
        public virtual ICollection<ObjRoots_DocumentPageInstance> ObjRoots_DocumentPageInstance { get; set; }
        public virtual ICollection<ObjRoots_PageField> ObjRoots_PageField { get; set; }
        public virtual ICollection<ObjRoots_PageField> ObjRoots_PageField1 { get; set; }
    }
}
