//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots
    {
        public System.Guid Id { get; set; }
        public System.Guid HierId { get; set; }
        public bool IsActive { get; set; }
        public bool IsTestData { get; set; }
        public string SearchKey { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> CurrentUserId { get; set; }
    
        public virtual ObjRoots_ComboGroup ObjRoots_ComboGroup { get; set; }
        public virtual ObjRoots_ComboValue ObjRoots_ComboValue { get; set; }
        public virtual ObjRoots_Document ObjRoots_Document { get; set; }
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
        public virtual ObjRoots_DocumentInstanceLog ObjRoots_DocumentInstanceLog { get; set; }
        public virtual ObjRoots_DocumentInstanceMessage ObjRoots_DocumentInstanceMessage { get; set; }
        public virtual ObjRoots_DocumentPackage ObjRoots_DocumentPackage { get; set; }
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage { get; set; }
        public virtual ObjRoots_DocumentPageInstance ObjRoots_DocumentPageInstance { get; set; }
        public virtual ObjRoots_DocumentType ObjRoots_DocumentType { get; set; }
        public virtual ObjRoots_ExternalGuidFillToken ObjRoots_ExternalGuidFillToken { get; set; }
        public virtual ObjRoots_MergeField ObjRoots_MergeField { get; set; }
        public virtual ObjRoots_Notification ObjRoots_Notification { get; set; }
        public virtual ObjRoots_PageField ObjRoots_PageField { get; set; }
        public virtual ObjRoots_PageImage ObjRoots_PageImage { get; set; }
    }
}
