//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoots_DocumentPageInstance
    {
        public Nullable<bool> Approved { get; set; }
        public string NotApprovedReason { get; set; }
        public System.Guid DocumentPageId { get; set; }
        public string UserComments { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> FillDate { get; set; }
        public System.Guid DocumentInstanceId { get; set; }
        public byte[] PreRenderedPDFPage { get; set; }
        public System.Guid Id { get; set; }
        public byte[] SubmittedData { get; set; }
        public byte[] DraftData { get; set; }
    
        public virtual ObjRoots ObjRoots { get; set; }
        public virtual ObjRoots_DocumentInstance ObjRoots_DocumentInstance { get; set; }
        public virtual ObjRoots_DocumentPage ObjRoots_DocumentPage { get; set; }
    }
}
