//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageFieldTranslations
    {
        public System.Guid Id { get; set; }
        public System.Guid DocumentPageTranslationId { get; set; }
        public System.Guid PageFieldId { get; set; }
        public string Tooltip { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public string Html { get; set; }
        public string InitialValue { get; set; }
        public string SelectTitle { get; set; }
        public string Href { get; set; }
    
        public virtual DocumentPageTranslations DocumentPageTranslations { get; set; }
        public virtual ObjRoots_PageField ObjRoots_PageField { get; set; }
    }
}
