//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_DataMotions
    {
        public int DataMotionId { get; set; }
        public System.DateTime DateExcecuted { get; set; }
        public bool IsPreDeploy { get; set; }
    }
}
