//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTokens
    {
        public long Id { get; set; }
        public string TokenString { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
    }
}
